proxy_cache_path /var/www/cache levels=1:2 keys_zone=botge-cache:8m max_size=5000m inactive=6000m;
proxy_temp_path /var/www/cache/tmp;

server {
  listen 80;
  listen [::]:80;

  proxy_cache botge-cache;
  proxy_cache_valid 200 302 6000m;
  proxy_cache_valid 404 1m;
  proxy_ssl_server_name on;

  location /7tv/ {
    proxy_pass https://cdn.7tv.app/;
  }

  location /bttv/ {
    proxy_pass https://cdn.betterttv.net/;
  }

  location /ffz/ {
    proxy_pass https://cdn.frankerfacez.com/;
  }

  location /twitch/ {
    proxy_pass https://static-cdn.jtvnw.net/;
  }
}
